chocoapp/dataeng-dagger

dagger/dag_creator/airflow/operators/aws_athena_operator.py

In the athena transformation, atm partitioned_by attribute was split by characters instead of split by comma.

Splitting partition by by comma

---

dagger/pipeline/tasks/athena_transform_task.py

The attribute's validator was list, but we need string, so we can split into a list later

Fixing attribute type

---

dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py

Fix `psycopg2.errors.ActiveSqlTransaction: ALTER TABLE ALTER COLUMN cannot run inside a transaction block` error by turning on autocommit for the alter column commands section.

adding autocommit for alter columns command

---

dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py

Removing unnecessary parameter. Splitting statements will by default passed to the hook.

Removing unneccessary parameter

---

dagger/dag_creator/airflow/operators/aws_athena_operator.py
reqs/base.txt

We have some failures during cleanup when we delete all partitions of the temp tables because of S3 SlowDown. In these cases the job runs from scratch which means that the cleanup will need to clean even more data for the second time. Instead retying the full task, added retry just for the cleanup function inside the operator

Adding retry with tenacity

---

dagger/dag_creator/airflow/operator_creators/redshift_load_creator.py

The problem with using the redshift loader right now is that when the path is read from the s3 input, the 
```sql
CREATE TABLE <table name> from <path>
```
where `path = x/y/z`, uses this `path` as a prefix. This means that all files that have the path as a prefix would be loaded(like `x/y/z*`). 
This behaviour breaks the redshift loaders when there are two objects(in this case dbt models) that have the same prefix path.
This PR adds the behavior such that the input paths always contain a trailing backslash

changed how the input path is used in the redshift loader

---

dagger/dag_creator/airflow/operator_creators/dbt_creator.py
dagger/pipeline/tasks/dbt_task.py

- Add the new mandatory `dbt_command` parameter. This way, we can customise the dbt operation and not only use the default `build` by other processes.

Feature: Add the new mandatory dbt command parameter

---

dagger/dag_creator/airflow/dag_creator.py

Dagger doesn't have a proper feature to create one external sensor for multiple tasks in the same DAG. It will throw error: `DuplicateTaskIdFound(f"Task id '{task_id}' has already been added to the DAG")` when we set multiple tasks in the same DAG as downstream for a single external sensor.
This PR is to introduce/ fix this feature with a quick solution.
- Issue:
When we loop over the ` to_task_ids`, we will create a new external task sensor object 
```
external_task_sensor = self._get_external_task_sensor(
from_task_id, to_task_id
)
``` 
for each loop. In this way, Airflow will be repeated to create the sensor in the same DAG --> which will raise the `DuplicateTaskIdFound`.
- Solution:
we add another attribute `sensor_dict` to save the generated `external_task_sensor` for each `to_pipe` …

DATA-1477 fix: one external sensor for multiple tasks in one DAG

---

dagger/dag_creator/airflow/dag_creator.py

Jira Ticket: [DATA=1500](https://choco.atlassian.net/browse/DATA-1500)
Sensor was not giving slack alert when failed.
Root Cause: When sensor operator was created the dag object was not passed into the operator as a parameter, hence the default arguments (which contains what to do on failure) were also not passed into the sensor operator.
This fix is adding the dag object into the sensor operator on creation time, making sure that all default arguments, like the on_failure_callback function is also passed in.
tested in [tst environment](https://airflow.datatst.choco.com/task?dag_id=core-salesforce&task_id=analytics_engineering-dbt_hourly-dbt_hourly-sensor&execution_date=2022-04-07T23%3A30%3A00%2B00%3A00)

Adding sensor to proper dag

---

dagger/dag_creator/airflow/dag_creator.py

The external sensor is poking the wrong external tag when checking the status of the external dag.
At the moment, we are using         
```
from_pipeline_name = external_sensor_name.split("-")[0]
from_task_name = external_sensor_name.split("-")[1]
```
to define the `from_pipeline_name` and `from_task_name` to create the external sensor object.
However, there might be multiple `-` in the external_sensor_name. For example: `core-salesforce-account_dimension_updater-sensor`, with the current way, we will get the wrong `from_pipeline_name` and `from_task_name` which will create a sensor linked to a wrong/ non-existing external task.
- Get the sensor related params directly from the graph and export it as a dictionary
- Use the params from this dictionary when creating the sensor instead of …

fix: _get_external_task_sensor

---

dagger/dag_creator/airflow/dag_creator.py

There was a bug associating external task sensors for a particular pipeline.
The `_sensor_dict` for a particular pipeline was overwritten for every `task_id`, instead of appending to it. 
This PR fixes this behavior so that all sensors are appended/updated instead of overwritten

fix external sensor bug

---

dagger/dag_creator/airflow/operators/postgres_operator.py

For the incremental redshift dim load I need to run multiple sql commands in one query, but this is only possible if I enable the split_statment attribute, which is going to actually run all sql statements in the query as a separate sql query.

Turning split_statements on by default

---

dagger/dag_creator/airflow/operator_creators/dbt_creator.py
dagger/pipeline/tasks/dbt_task.py
dockers/airflow/airflow.cfg

Rename the `profile_name` param in dbt task parameters to `target_name` 
(According to the [dbt documentation](https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml) what we were naming `profile_name`  is actually `target_name` )

feat: rename profile_name to target_name

---

dagger/dag_creator/airflow/operator_creators/batch_creator.py
dagger/dag_creator/airflow/operator_creators/spark_creator.py
dagger/dag_creator/airflow/operators/awsbatch_operator.py

[DATA-1804](https://choco.atlassian.net/browse/DATA-1804)
The newest version of the official aws batch operator collects all logs from cloudwatch, however there is a bug inside and because of that it cannot log the link to the cloudwatch logs, which is an important peace of information.
1. Switching to official Batch operator
2. Create a custom batch operator inhereted from the official one, which ovverwrites the monitor_job function and prints the proper link to cloudwatch logs in the logs.
[DATA-1804]: https://choco.atlassian.net/browse/DATA-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Switching to official batch operator

---

dagger/utilities/dbt_config_parser.py
tests/fixtures/modules/dbt_config_parser_fixtures_databricks.py

fix: _get_model_data_location in DatabricksDBTConfigParser #38
the `location_root` already has the `schema` in the path

fix: _get_model_data_location in DatabricksDBTConfigParser

---

dagger/utilities/dbt_config_parser.py
tests/fixtures/modules/dbt_config_parser_fixtures_athena.py
tests/fixtures/modules/dbt_config_parser_fixtures_databricks.py
tests/utilities/test_dbt_config_parser.py

Adjust the dbt config parser so that:
- If the node is a DBT source, an Athena table task is generated.
- If the node is an ephemeral model, a dummy task is generated, and tasks for its dependent nodes are recursively generated.
- If the node is a staging model (preparation model) and not materialized as a table, a table task is generated along with tasks for its dependent nodes.
- For other nodes, a table task is generated. If the node is materialized as a table, an additional S3 task is also generated.
Tested in [airflow-staging](https://airflow.datastg.choco.com/dags/analytics_engineering-dbt_hourly/grid?dag_run_id=scheduled__2024-06-15T00%3A45%3A00%2B00%3A00&task_id=dim_supplier_choco_ai_setup_rs_loader&tab=logs)
example:

DATA-1996: adjust the dbt config parser so that view/ephemeral staging layer doesnt need a task

---

dagger/dag_creator/airflow/operator_creators/reverse_etl_creator.py
dagger/pipeline/tasks/reverse_etl_task.py

Add a new param `full_refresh` for reverse_etl task to enable the full refresh

feat: add param _full_refresh in the reverse_etl task

---

dagger/dag_creator/airflow/operator_creators/dbt_creator.py

Right now we add all inputs/outputs from the dbt task yaml to the batch command, the thing is we have all the upstream sensors and also the soda sensors and that command is getting pretty big unnecessarily. for one table is even bigger than the size supported by batch

Removing unnecessary inputs/outputs from command

---

dagger/dag_creator/airflow/operator_creators/reverse_etl_creator.py
dagger/pipeline/tasks/reverse_etl_task.py

Add `_input_table_columns_to_include` and `_input_table_columns_to_exclude` to the reverse_etl task param, so that we can choose what fields to upload to the dynamo/glue

feat: add param _columns_to_include and _columns_to_exclude in the reverse_etl task

---

dagger/pipeline/tasks/reverse_etl_task.py

The `validator=bool` was not working as expected.
This is how it works:
if we use validator=bool,
then the parsed_value = bool(input_value)
However, this will be the result of some examples:
```
bool("")      # False, because the empty string is “falsy”
bool("False") # True, because any non‐empty string is “truthy”
bool("foo")   # True
```
So:
"" → False
anything else (e.g. "False", "0", "anything") → True
This is not what we want. So, we should use `str` as validator and then use parse_boolean as type in the python script to handle this input.

fix: wrong validator for full_refresh

---

dagger/dag_creator/airflow/operators/awsbatch_operator.py

Print cloudwatch logs to deferrable batch job.
Test run: https://airflow.datastg.choco.com/dags/core-orders/grid?dag_run_id=scheduled__2025-06-23T00%3A45%3A00%2B00%3A00&task_id=order_delivery_check_modified_delta_fact_soda&tab=logs

feat: add real logs for deferrable batch job

---

dagger/pipeline/pipeline.py

[DATA-2387](https://choco.atlassian.net/browse/DATA-2387)
After upgrading to Airflow 2.11, there is more strict type checks that are performed. 
As a result, when we use `dagrun_timeout`, like [here](https://github.com/chocoapp/dataeng-airflow-dags/blob/5ef4a71f1e9ec1d7dbc4fddf92f8640dfa2c54b8/dags/dataeng/emr/scale_down/pipeline.yaml#L11) the dags fail to load on airflow because `dagrun_timeout` expects a `timedelta` but we input an `int`.
As a quick fix, I use the `eval` method to evaluate the input `dagrun_timeout`, provided that the value we input is something like `"timedelta(seconds=1500)"`. you can see this [here](https://github.com/chocoapp/dataeng-airflow-dags/blob/0cd44dbdc193fde7f204bc22fea519351ce75126/dags/dataeng/emr/scale_down/pipeline.yaml#L11).
[DATA-2387]: …

parse dagrun_timeout as a timedelta instead of int
